name: Gold price CSV (daily)

on:
  workflow_dispatch:          # تشغيل يدوي
  schedule:
    - cron: '0 15 * * *'      # يوميًا 18:00 بتوقيت بيروت (15:00 UTC)

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch latest gold price and update CSV
        run: |
          set -euo pipefail
          OUT="XAUUSD_live.csv"
          test -f "$OUT" || echo "Date,Close" > "$OUT"

          # آخر 30 يوم (بدون Python)
          EPOCH_NOW=$(date +%s)
          EPOCH_PAST=$(date -d '30 days ago' +%s)

          # المحاولة 1: Yahoo (عقود الذهب GC=F)
          YURL="https://query1.finance.yahoo.com/v7/finance/download/GC=F?period1=${EPOCH_PAST}&period2=${EPOCH_NOW}&interval=1d&events=history&includeAdjustedClose=true"
          curl -sSL -A "Mozilla/5.0" "$YURL" -o /tmp/yahoo.csv || true

          DATE=""; CLOSE=""
          if [ -s /tmp/yahoo.csv ]; then
            LAST=$(tail -n 1 /tmp/yahoo.csv || true)
            DATE=$(echo "$LAST" | cut -d, -f1)
            CLOSE=$(echo "$LAST" | cut -d, -f5)
          fi

          # المحاولة 2: Stooq (XAUUSD)
          if [ -z "${CLOSE:-}" ] || [ "$CLOSE" = "null" ]; then
            curl -sSL -A "Mozilla/5.0" "https://stooq.com/q/d/l/?s=xauusd&i=d" -o /tmp/stooq.csv || true
            if [ -s /tmp/stooq.csv ]; then
              LAST=$(tail -n 1 /tmp/stooq.csv || true)
              DATE=$(echo "$LAST" | cut -d, -f1)
              CLOSE=$(echo "$LAST" | cut -d, -f5)
            fi
          fi

          # إذا جبنا تاريخ/سعر، أضِف السطر إذا جديد
          if [ -n "${DATE:-}" ] && [ -n "${CLOSE:-}" ]; then
            LAST_DATE=$(tail -n 1 "$OUT" | cut -d, -f1 || echo "")
            if [ "$LAST_DATE" != "$DATE" ]; then
              echo "$DATE,$CLOSE" >> "$OUT"
            fi
          else
            echo "No price fetched (Yahoo & Stooq failed)"; exit 0
          fi

      - name: Commit CSV (if changed)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add XAUUSD_live.csv
          git commit -m "Update XAUUSD_live.csv" || echo "No changes"
          git push
