name: Gold price CSV (5min)

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # كل 5 دقايق بالـUTC

permissions:
  contents: write

concurrency:
  group: gold-csv-5min
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update 5-min CSV (Date,Close)
        shell: bash
        run: |
          set -euo pipefail
          OUT="XAUUSD_5min.csv"
          [ -f "$OUT" ] || echo "Date,Close" > "$OUT"

          # سطر حي من Stooq (XAUUSD)
          CSV=$(curl -sS -L -A "Mozilla/5.0" "https://stooq.com/q/l/?s=xauusd&f=sd2t2ohlcv&h&e=csv" || true)
          LINE=$(printf '%s\n' "$CSV" | sed -n '2p' | tr -d '\r' || true)
          PRICE=$(printf '%s' "$LINE" | awk -F, '{print $7}')

          # طابع زمني مضبوط على الـtick الحالي (الـrun أصلاً على دقيقة 0/5/10...)
          TS=$(date -u +'%Y-%m-%dT%H:%M:00Z')
          LAST_TS=$(tail -n 1 "$OUT" | cut -d, -f1 || echo "")

          # لو ما قدرنا نقرأ رقم، ما منضيف شي (منعيد بعد 5 دق)
          if ! [[ "$PRICE" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
            echo "No price parsed; skip"
            exit 0
          fi

          if [ "$LAST_TS" != "$TS" ]; then
            echo "$TS,$PRICE" >> "$OUT"
            echo "Appended $TS,$PRICE"
          else
            echo "Already have row for $TS"
          fi

      - name: Commit CSV (if changed)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add XAUUSD_5min.csv || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "5-min gold price update"
          git push
