name: Gold price CSV (hourly)

on:
  workflow_dispatch:          # تشغيل يدوي
  schedule:
    - cron: '0 * * * *'       # كل ساعة عند الدقيقة 00 (UTC)

permissions:
  contents: write

concurrency:
  group: gold-csv
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch price and update CSVs
        shell: bash
        run: |
          set -euo pipefail

          OUT_H="XAUUSD_hourly.csv"
          OUT_D="XAUUSD_live.csv"
          [ -f "$OUT_H" ] || echo "DatetimeUTC,Price" > "$OUT_H"
          [ -f "$OUT_D" ] || echo "Date,Close" > "$OUT_D"

          # ----- Hourly price (Yahoo -> fallback Stooq) -----
          PRICE=""
          YJSON=$(curl -sS -L -A "Mozilla/5.0" "https://query1.finance.yahoo.com/v7/finance/quote?symbols=GC=F" || true)
          if [ -n "$YJSON" ]; then
            PRICE=$(echo "$YJSON" | tr -d '\n' | sed -nE 's/.*"regularMarketPrice":([0-9.]+).*/\1/p' | head -n1 || true)
          fi
          if [ -z "$PRICE" ]; then
            SCSV=$(curl -sS -L -A "Mozilla/5.0" "https://stooq.com/q/l/?s=xauusd&f=sd2t2ohlcv&h&e=csv" || true)
            PRICE=$(echo "$SCSV" | awk -F, 'NR==2{print $7}' || true)
          fi

          if [ -n "${PRICE:-}" ]; then
            DATE_H=$(date -u +'%Y-%m-%dT%H:00:00Z')                # طابع زمني على رأس الساعة (UTC)
            LAST_H=$(tail -n 1 "$OUT_H" | cut -d, -f1 || echo "")
            if [ "$LAST_H" != "$DATE_H" ]; then
              echo "$DATE_H,$PRICE" >> "$OUT_H"
            fi
          else
            echo "No hourly price fetched"
          fi

          # ----- Daily close (Stooq daily CSV) -----
          curl -sS -L -A "Mozilla/5.0" "https://stooq.com/q/d/l/?s=xauusd&i=d" -o /tmp/stooq_daily.csv || true
          if [ -s /tmp/stooq_daily.csv ]; then
            LAST=$(tail -n +2 /tmp/stooq_daily.csv | tail -n 1 || true)
            DDATE=$(echo "$LAST" | cut -d, -f1)
            DCLOSE=$(echo "$LAST" | cut -d, -f5)
            LAST_D=$(tail -n 1 "$OUT_D" | cut -d, -f1 || echo "")
            if [ -n "${DDATE:-}" ] && [ -n "${DCLOSE:-}" ] && [ "$LAST_D" != "$DDATE" ]; then
              echo "$DDATE,$DCLOSE" >> "$OUT_D"
            fi
          fi

      - name: Commit CSVs (if changed)
        shell: bash
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add XAUUSD_hourly.csv XAUUSD_live.csv || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Hourly gold price update"
          git push
