name: Gold price CSV (minutely)

on:
  workflow_dispatch:          # تشغيل يدوي من Actions
  schedule:
    - cron: '* * * * *'       # محاولة تشغيل كل دقيقة (UTC)

permissions:
  contents: write

concurrency:
  group: gold-csv
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      # إذا عندك Cloudflare Worker حطه هون (اختياري)
      # مثال: https://goldprice-proxy.<yourname>.workers.dev?s=GC=F
      WORKER_URL: ''
      # الرمز: GC=F (عقود ذهب) أو XAUUSD=X (سبوت)
      Y_SYMBOL: 'GC=F'
    steps:
      - uses: actions/checkout@v4

      - name: Fetch price (minutely) and update CSV
        shell: bash
        run: |
          set -euo pipefail
          OUT_M="XAUUSD_minutely.csv"
          [ -f "$OUT_M" ] || echo "DatetimeUTC,Price,Source" > "$OUT_M"

          PRICE=""
          SRC=""

          # 1) لو في Worker مفعّل
          if [ -n "${WORKER_URL}" ]; then
            J=$(curl -sS -L "${WORKER_URL}" || true)
            PRICE=$(echo "$J" | sed -nE 's/.*"price":\s*([0-9.]+).*/\1/p' | head -n1 || true)
            if [ -n "${PRICE}" ]; then SRC="worker"; fi
          fi

          # 2) Yahoo JSON
          if [ -z "${PRICE}" ]; then
            YJSON=$(curl -sS -L -A "Mozilla/5.0" "https://query1.finance.yahoo.com/v7/finance/quote?symbols=${Y_SYMBOL}" || true)
            PRICE=$(echo "$YJSON" | tr -d '\n' | sed -nE 's/.*"regularMarketPrice":\s*([0-9.]+).*/\1/p' | head -n1 || true)
            if [ -n "${PRICE}" ]; then SRC="yahoo"; fi
          fi

          # 3) fallback: Stooq (آخر سعر Close)
          if [ -z "${PRICE}" ]; then
            SCSV=$(curl -sS -L -A "Mozilla/5.0" "https://stooq.com/q/l/?s=xauusd&f=sd2t2ohlcv&h&e=csv" || true)
            PRICE=$(echo "$SCSV" | awk -F, 'NR==2{print $7}' || true)
            if [ -n "${PRICE}" ]; then SRC="stooq"; fi
          fi

          # اكتب سطر جديد على رأس كل دقيقة (UTC) إذا لقينا سعر
          if [ -n "${PRICE}" ]; then
            DT=$(date -u +'%Y-%m-%dT%H:%M:00Z')
            LAST_DT=$(tail -n 1 "$OUT_M" | cut -d, -f1 || echo "")
            if [ "$LAST_DT" != "$DT" ]; then
              echo "$DT,$PRICE,${SRC:-unknown}" >> "$OUT_M"
            fi
          else
            echo "No price fetched this minute"
          fi

      - name: Commit CSV (if changed)
        shell: bash
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add XAUUSD_minutely.csv || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Minutely gold price update"
          git push
